// Copyright (C) 2008 Naoyuki Hirayama.
// All Rights Reserved.

// $Id$

#include "caper_ast.hpp"
#include "caper_generate_cpp.hpp"
#include "caper_format.hpp"
#include "caper_stencil.hpp"
#include "caper_finder.hpp"
#include <algorithm>
#include <boost/tuple/tuple.hpp>
#include <boost/tuple/tuple_comparison.hpp>
#include <boost/filesystem/path.hpp>

namespace {

std::string make_type_name(const Type& x) {
    switch(x.extension) {
        case Extension::None:
            return x.name;
        case Extension::Star:
        case Extension::Plus:
        case Extension::Slash:
            return x.name + "[]";
        case Extension::Question:
            return x.name + "[]";
        default:
            assert(0);
            return "";
    }
}
        
void make_signature(
    const std::map<std::string, Type>&      nonterminal_types,
    const tgt::parsing_table::rule_type&    rule,
    const SemanticAction&                   sa,
    std::vector<std::string>&               signature) {
    // function name
    signature.push_back(sa.name);

    // return value
    signature.push_back(
        make_type_name(*finder(nonterminal_types, rule.left().name())));

    // arguments
    for (const auto& arg: sa.args) {
        signature.push_back(make_type_name(arg.type));
    }
}

} // unnamed namespace

void generate_d(
    const std::string&                  src_filename,
    std::ostream&                       os,
    const GenerateOptions&              options,
    const std::map<std::string, Type>&,
    const std::map<std::string, Type>&  nonterminal_types,
    const std::vector<std::string>&     tokens,
    const action_map_type&              actions,
    const tgt::parsing_table&           table) {

    std::string module_name =
        boost::filesystem::path(src_filename).stem().string();

    // notice / URL / module / imports
    stencil(
        os, R"(
// This file was automatically generated by Caper.
// (http://jonigata.github.io/caper/caper.html)

module ${module_name};

import std.array;
import std.stdio;

)",
        {"module_name", module_name}
        );

    if (!options.external_token) {
        // token enumeration
        stencil(
            os, R"(
enum Token {
$${tokens}
}

string tokenLabel(Token t) {
    static string[] labels = [
$${labels}
    ];
    return labels[t];
}

)",
            {"tokens", [&](std::ostream& os){
                    for(const auto& token: tokens) {
                        stencil(
                            os, R"(
    ${prefix}${token},
)",
                            {"prefix", options.token_prefix},
                            {"token", token}
                            );
                    }
                }},
            {"labels", [&](std::ostream& os){
                    for(const auto& token: tokens) {
                        stencil(
                            os, R"(
        "${prefix}${token}",
)",
                            {"prefix", options.token_prefix},
                            {"token", token}
                            );
                    }
                }}
            );

    }

    // stack
    stencil(
        os, R"(
class Stack(T) {
public:
    this() { _gap = 0; }

    void rollbackTmp() {
        _gap = _stack.length;
        _tmp.length = 0;
    }

    void commitTmp() {
        // expect not to throw
        _stack.length = _gap;
        _stack ~= _tmp;
        _tmp.length = 0;
    }
    bool push(T f) {
        _tmp ~= f;
        return true;
    }
	   
    void pop(uint n) {
        if (_tmp.length < n) {
            n -= _tmp.length;
            _tmp.length = 0;
            _gap -= n;
        } else {
            _tmp.length -= n;
        }
    }

    T* top() {
        assert(0 < depth());
        if (0 < _tmp.length) {
            return &_tmp.back;
        } else {
            return &_stack[_gap - 1];
        }
    }
	   
    T* getArg(uint base, uint index) {
        uint n = _tmp.length;
        if (base - index <= n) {
            return &_tmp[n - (base - index)];
        } else {
            return &_stack[_gap - (base - n) + index];
        }
    }
	   
    void clear() {
        _stack.length = 0;
        _tmp.length = 0;
        _gap = 0; 
    }
	   
    bool empty() {
        if (0 < _tmp.length) {
            return false;
        } else {
            return _gap == 0;
        }
    }
	   
    uint depth() {
        return _gap + _tmp.length;
    }
	   
    T* nth(uint index) {
        if (_gap <= index) {
            return &_tmp[index - _gap];
        } else {
            return &_stack[index];
        }
    }

    void swapTopAndSecond() {
        uint d = depth();
        assert(2 <= d);
        T x = *nth(d - 1);
        *nth(d - 1) = *nth(d - 2);
        *nth(d - 2) = x;
    }

private:
    T[] _stack;
    T[] _tmp;
    uint _gap;
	   
};

)");

    // parser class header
    stencil(
        os, R"(
class Parser(Value, SemanticAction) {
    alias Token TokenType;
    alias Value ValueType;

    enum Nonterminal {
)",
        {"token_parameter", options.external_token ? "class Token, " : ""},
        {"default_stack_size", options.dont_use_stl ? "1024" : "0"}
        );

    for (const auto& nonterminal_type: nonterminal_types) {
        stencil(
            os, R"(
        ${nonterminal_name},
)",
            {"nonterminal_name", nonterminal_type.first}
            );
    }
    
    stencil(
        os, R"(
    }

    this(SemanticAction sa){ _sa = sa; reset(); }

    void reset() {
        _error = false;
        _accepted = false;
        _stack = new typeof(_stack);
        clearStack();
        rollbackTmpStack();
        ValueType defaultValue;
        if (pushStack(${first_state}, defaultValue)) {
            commitTmpStack();
        } else {
            _sa.stack_overflow();
            _error = true;
        }
    }

    bool post(TokenType token, ValueType value) {
        rollbackTmpStack();
        _error = false;
        while((stackTop().entry.state)(this, token, value)){ }
        if (!_error) {
            commitTmpStack();
        } else {
            recover(token, value);
        }
        return _accepted || _error;
    }

    bool accept(out ValueType v) {
        assert(_accepted);
        if (_error) { return false; }
        v = _accepted_value;
        return true;
    }

    bool error() { return _error; }

)",
        {"first_state", table.first_state()}
        );

    // implementation
    stencil(
        os, R"(
private:
    alias typeof(this) SelfType;
    alias bool function(SelfType, TokenType, ValueType) StateType;
    alias int function(Nonterminal) GotofType;

    bool        _accepted;
    bool        _error;
    ValueType   _accepted_value;

    SemanticAction _sa;

    struct TableEntry {
        StateType   state;
        GotofType   gotof;
        bool        handleError;
    };

    struct StackFrame {
        TableEntry* entry;
        ValueType   value;
        int         sequenceLength;
    };

    struct Range {
        int begin;
        int end;
    };

)",
        {"token_paremter", options.external_token ? "Token, " : ""}
        );

    // stack operation
    stencil(
        os, R"(
    Stack!(StackFrame) _stack;

    bool pushStack(int stateIndex, ValueType v, int sl = 0) {
	bool f = _stack.push(StackFrame(entry(stateIndex), v, sl));
        assert(!_error);
        if (!f) { 
            _error = true;
            _sa.stack_overflow();
        }
        return f;
    }

    void popStack(uint n) {
$${pop_stack_implementation}
    }

    StackFrame* stackTop() {
        return _stack.top();
    }

    ValueType* getArg(uint base, uint index) {
        return &_stack.getArg(base, index).value;
    }

    void clearStack() {
        _stack.clear();
    }

    void rollbackTmpStack() {
        _stack.rollbackTmp();
    }

    void commitTmpStack() {
        _stack.commitTmp();
    }

)",
        {"pop_stack_implementation", [&](std::ostream& os) {
                if (options.allow_ebnf) {
                    stencil(
                        os, R"(
        int nn = cast(int)n;
        while(nn--) {
            _stack.pop(1 + _stack.top().sequenceLength);
        }
)"
                        );
                } else {
                    stencil(
                        os, R"(
        _stack.pop(n);
)"
                        );
                }
            }}
        );

    if (options.recovery) {
        stencil(
            os, R"(
    void recover(TokenType token, ValueType value) {
        rollbackTmpStack();
        _error = false;
$${debmes:start}
        while(!stackTop().entry.handleError) {
            popStack(1);
            if (_stack.empty()) {
$${debmes:failed}
                _error = true;
                return;
            }
        }
$${debmes:done}
        // post error_token;
$${debmes:post_error_start}
        ValueType defaultValue;
        while((stackTop().entry.state)(this, Token.${recovery_token}, defaultValue)){}
$${debmes:post_error_done}
        commitTmpStack();
        // repost original token
        // if it still causes error, discard it;
$${debmes:repost_start}
        while((stackTop().entry.state)(this, token, value)){ }
$${debmes:repost_done}
        if (!_error) {
            commitTmpStack();
        }
        if (token != Token.${token_eof}) {
            _error = false;
        }
    }

)",
            {"recovery_token", options.token_prefix + options.recovery_token},
            {"token_eof", options.token_prefix + "eof"},
            {"debmes:start", {
                    options.debug_parser ?
                        R"(        stderr.writefln("recover rewinding start: stack depth = %d", _stack.depth());
)" :
                        ""}},
            {"debmes:failed", {
                    options.debug_parser ?
                        R"(        stderr.writeln("recover rewinding failed");
)" :
                        ""}},
            {"debmes:done", {
                    options.debug_parser ?
                        R"(        stderr.writeln("recover rewinding done: stack depth = %d", _stack.depth());
)":
                        ""}},
            {"debmes:post_error_start", {
                    options.debug_parser ?
                        R"(        stderr.writeln("posting error token");
)" :
                        ""}},
            {"debmes:post_error_done", {
                    options.debug_parser ?
                        R"(        stderr.writeln("posting error token done");
)" :
                        ""}},
            {"debmes:repost_start", {
                    options.debug_parser ?
                        R"(        stderr.writeln("reposting original token");
)" :
                        ""}},
            {"debmes:repost_done", {
                    options.debug_parser ? 
                        R"(        stderr.writeln("reposting original token done");
)" :
                        ""}}
            );
    } else {
        stencil(
            os, R"(
    void recover(TokenType, ValueType) {
    }

)"
            );
    }

    if (options.allow_ebnf) {
        stencil(
            os, R"(
    // EBNF support member functions
    bool seq_head(Nonterminal nonterminal, int base) {
        // case '*': base == 0
        // case '+': base == 1
        int dest = (stack_nth_top(base).entry.gotof)(nonterminal);
        ValueType defaultValue;
        return pushStack(dest, defaultValue, base);
    }
    bool seq_trail(Nonterminal nonterminal, int base) {
        // '*', '+' trailer
        _stack.swapTopAndSecond();
        stackTop().sequenceLength++;
        return true;
    }
    bool seq_trail2(Nonterminal nonterminal, int base) {
        // '/' trailer
        _stack.swapTopAndSecond();
        popStack(1); // erase delimiter
        _stack.swapTopAndSecond();
        stackTop().sequenceLength++;
        return true;
    }
    bool opt_nothing(Nonterminal nonterminal, int base) {
        // same as head of '*'
        return seq_head(nonterminal, base);
    }
    bool opt_just(Nonterminal nonterminal, int base) {
        // same as head of '+'
        return seq_head(nonterminal, base);
    }
    Range seq_get_range(int base, int index) {
        // returns beg = end if length = 0 (includes scalar value)
        // distinguishing 0-length-vector against scalar value is
        // caller's responsibility
        int n = base - index;
        int prevActualIndex;
        int actualIndex = _stack.depth();
        while(n--) {
            actualIndex--;
            prevActualIndex = actualIndex;
            actualIndex -= _stack.nth(actualIndex).sequenceLength;
        }
        return Range(actualIndex, prevActualIndex);
    }
    ValueType seq_get_arg(int base, int index) {
        Range r = seq_get_range(base, index);
        // multiple value appearing here is not supported now
        return _stack.nth(r.begin).value;
    }
    ValueType[] seq_get_seq(int base, int index) {
        Range r = seq_get_range(base, index);

        ValueType[] a = [];
        for(int i = r.begin ; i < r.end ; i++) {
            a ~= _stack.nth(i).value;
        }        
        return a;
    }
    StackFrame* stack_nth_top(int n) {
        Range r = this.seq_get_range(n + 1, 0);
        // multiple value appearing here is not supported now
        return _stack.nth(r.begin);
    }
)"
            );
    }


    stencil(
        os, R"(
    bool call_nothing(Nonterminal nonterminal, int base) {
        popStack(base);
        int dest_index = (stackTop().entry.gotof)(nonterminal);
        ValueType defaultValue;
        return pushStack(dest_index, defaultValue);
    }

)"
        );

    // member function signature -> index
    std::map<std::vector<std::string>, int> stub_indices;
    {
        // member function name -> count
        std::unordered_map<std::string, int> stub_counts; 

        // action handler stub
        for (const auto& pair: actions) {
            const auto& rule = pair.first;
            const auto& sa = pair.second;

            if (sa.special) {
                continue;
            }

            const auto& rule_type =
                *finder(nonterminal_types, rule.left().name());

            // make signature
            std::vector<std::string> signature;
            make_signature(
                nonterminal_types,
                rule,
                sa,
                signature);

            // skip duplicated
            if (0 < stub_indices.count(signature)) {
                continue;
            }

            // make function name
            if (stub_counts.count(sa.name) == 0) {
                stub_counts[sa.name] = 0;
            }
            int stub_index = stub_counts[sa.name];
            stub_indices[signature] = stub_index;
            stub_counts[sa.name] = stub_index+1;

            // header
            stencil(
                os, R"(
    bool call_${stub_index}_${sa_name}(Nonterminal nonterminal, int base${args}) {
)",
                {"stub_index", stub_index},
                {"sa_name", sa.name},
                {"args", [&](std::ostream& os) {
                        for (size_t l = 0 ; l < sa.args.size() ; l++) {
                            os << ", int argIndex" << l;
                        }
                    }}
                );

            // check sequence conciousness
            std::string get_arg = "getArg";
            for (const auto& arg: sa.args) {
                if (arg.type.extension != Extension::None) {
                    get_arg = "seq_getArg";
                    break;
                }
            }

            // automatic argument conversion
            for (size_t l = 0 ; l < sa.args.size() ; l++) {
                const auto& arg = sa.args[l];
                if (arg.type.extension == Extension::None) {
                    stencil(
                        os, R"(
        ${arg_type} arg${index}; _sa.downcast(arg${index}, *${get_arg}(base, argIndex${index}));
)",
                        {"arg_type", make_type_name(arg.type)},
                        {"get_arg", get_arg},
                        {"index", l}
                        );
                } else {
                    stencil(
                        os, R"(
        ${arg_type} arg${index} = seq_get_seq(base, argIndex${index});
)",
                        {"arg_type", make_type_name(arg.type)},
                        {"index", l}
                        );
                }
            }

            // semantic action / automatic value conversion
            stencil(
                os, R"(
        ${nonterminal_type} r = _sa.${semantic_action_name}(${args});
        ValueType v; _sa.upcast(v, r);
        popStack(base);
        int dest_index = (stackTop().entry.gotof)(nonterminal);
        return pushStack(dest_index, v);
    }

)",
                {"nonterminal_type", make_type_name(rule_type)},
                {"semantic_action_name", sa.name},
                {"args", [&](std::ostream& os) {
                        bool first = true;
                        for (size_t l = 0 ; l < sa.args.size() ; l++) {
                            if (first) { first = false; }
                            else { os << ", "; }
                            os << "arg" << l;
                        }
                    }}
                );
        }
    }

    // states handler
    for (const auto& state: table.states()) {
        // state header
        stencil(
            os, R"(
    static bool state_${state_no}(SelfType self, TokenType token, ValueType value) {
$${debmes:state}
        switch(token) {
)",
            {"state_no", state.no},
            {"debmes:state", [&](std::ostream& os){
                    if (options.debug_parser) {
                        stencil(
                            os, R"(
        stderr.writefln("state_${state_no} << %s", tokenLabel(token));
)",
                            {"state_no", state.no}
                            );
                    }}}
            );

        // reduce action cache
        typedef boost::tuple<
            std::vector<std::string>,
            std::string,
            size_t,
            std::vector<int>>
            reduce_action_cache_key_type;
        typedef 
            std::map<reduce_action_cache_key_type,
                     std::vector<std::string>>
            reduce_action_cache_type;
        reduce_action_cache_type reduce_action_cache;

        // action table
        for (const auto& pair: state.action_table) {
            const auto& token = pair.first;
            const auto& action = pair.second;

            const auto& rule = action.rule();

            // action header 
            std::string case_tag =
                "Token." + options.token_prefix + tokens[token];

            // action
            switch (action.type()) {
                case zw::gr::action_shift:
                    stencil(
                        os, R"(
        case ${case_tag}:
            // shift
            self.pushStack(/*state*/ ${dest_index}, value);
            return false;
)",
                        {"case_tag", case_tag},
                        {"dest_index", action.dest_index()}
                        );
                    break;
                case zw::gr::action_reduce: {
                    size_t base = rule.right().size();
                    const std::string& rule_name = rule.left().name();

                    auto k = finder(actions, rule);
                    if (k && !(*k).special) {
                        const auto& sa = *k;

                        std::vector<std::string> signature;
                        make_signature(
                            nonterminal_types,
                            rule,
                            sa,
                            signature);

                        reduce_action_cache_key_type key =
                            boost::make_tuple(
                                signature,
                                rule_name,
                                base,
                                sa.source_indices);

                        reduce_action_cache[key].push_back(case_tag);
                    } else {
                        stencil(
                            os, R"(
        case ${case_tag}:
)",
                            {"case_tag", case_tag}
                            );
                        std::string funcname = "call_nothing";
                        if (k) {
                            const auto& sa = *k;
                            assert(sa.special);
                            funcname = sa.name;
                        }
                        stencil(
                            os, R"(
            // reduce
            return self.${funcname}(Nonterminal.${nonterminal}, /*pop*/ ${base});
)",
                            {"funcname", funcname},
                            {"nonterminal", rule.left().name()},
                            {"base", base}
                            );
                    }
                }
                    break;
                case zw::gr::action_accept:
                    stencil(
                        os, R"(
        case ${case_tag}:
            // accept
            self._accepted = true;
            self._accepted_value = *self.getArg(1, 0);
            return false;
)",
                        {"case_tag", case_tag}
                        );
                    break;
                case zw::gr::action_error:
                    stencil(
                        os, R"(
        case ${case_tag}:
            self._sa.syntax_error();
            self._error = true;
            return false;
)",
                        {"case_tag", case_tag}
                        );
                    break;
            }

            // action footer
        }

        // flush reduce action cache
        for(const auto& pair: reduce_action_cache) {
            const reduce_action_cache_key_type& key = pair.first;
            const std::vector<std::string>& cases = pair.second;

            const std::vector<std::string>& signature = key.get<0>();
            const std::string& nonterminal_name = key.get<1>();
            size_t base = key.get<2>();
            const std::vector<int>& arg_indices = key.get<3>();

            for (size_t j = 0 ; j < cases.size() ; j++){
                // fall through, be aware when port to other language
                stencil(
                    os, R"(
        case ${case}:
)",
                    {"case", cases[j]}
                    );
            }

            int index = stub_indices[signature];

            stencil(
                os, R"(
            // reduce
            return self.call_${index}_${sa_name}(Nonterminal.${nonterminal}, /*pop*/ ${base}${args});
)",
                {"index", index},
                {"sa_name", signature[0]},
                {"nonterminal", nonterminal_name},
                {"base", base},
                {"args", [&](std::ostream& os) {
                        for(const auto& x: arg_indices) {
                            os  << ", " << x;
                        }
                    }}
                );
        }

        // dispatcher footer / state footer
        stencil(
            os, R"(
        default:
            self._sa.syntax_error();
            self._error = true;
            return false;
        }
    }

)"
            );

        // gotof header
        stencil(
            os, R"(
    static int gotof_${state_no}(Nonterminal nonterminal) {
)",
            {"state_no", state.no}
            );
            
        // gotof dispatcher
        std::stringstream ss;
        stencil(
            ss, R"(
        switch(nonterminal) {
)"
            );
        bool output_switch = false;
        for (const auto& pair: state.goto_table) {
            stencil(
                ss, R"(
        case Nonterminal.${nonterminal}: return ${state_index};
)",
                {"nonterminal", pair.first.name()},
                {"state_index", pair.second}
                );
            output_switch = true;
        }

        // gotof footer
        stencil(
            ss, R"(
        default: assert(0); return false;
        }
)"
            );
        if (output_switch) {
            os << ss.str();
        } else {
            stencil(
                os, R"(
        assert(0);
        return true;
)"
                );
        }
        stencil(os, R"(
    }

)"
                );


    }

    // table
    stencil(
        os, R"(
    TableEntry* entry(int n) {
        static TableEntry entries[] = [
$${entries}
        ];
        return &entries[n];
    }

)",
        {"entries", [&](std::ostream& os) {
                int i = 0;
                for (const auto& state: table.states()) {
                    stencil(
                        os, R"(
            { &state_${i}, &gotof_${i}, ${handle_error} },
)",
                            
                        {"i", i},
                        {"handle_error", state.handle_error}
                        );
                    ++i;
                }                    
            }}
        );

    // parser class footer
    // namespace footer
    // once footer
    stencil(
        os,
        R"(
};

)"
        );
}
